define(function() {
    return {
        "properties": [{
            "name": "profileImageIsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "profileImageLeft",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "profileImageTop",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingTextIsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingLeft",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingTop",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "profileImageHeight",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "profileImageWidth",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "profileImageSrc",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "slidingMenuisVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingWidth",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingHeight",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerFlexHeight",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "menuControlFlexTop",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "menuControlFlexHeight",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "flxBotomIsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "imgHamIconCloseIsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnClickIsVisible",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnClickLeft",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnClickTop",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnClickText",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "leftMenuIconSrc",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "hamIconIsVisibility",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnClickHeight",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnClickWidth",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "slidingMenuDirection",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headerAnimation",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "profileImageType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerStyle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "slidingMenuSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "headingSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "subHeadingSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "menuItemTextSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "footerTextSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "menuItemHeaderTextSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "btnClickSkin",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "callbackMode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["removeAllMenuItem", "addMenuItems", "getSelectedValues", "showMenu", "hideMenu", "addMenuItems2", "removeAllMenuItem2"],
        "events": ["onClickFooter", "onProfileClick", "onApplyButtonClick", "onClickFooterShare", "onClickFooterHelp", "onItemClick", "onShowMenu", "onHideMenu"]
    }
});